
sudo: required

services:
    - docker

script:
    - docker build -t  anita15docker/node .
    - docker images anita15docker/node

before_deploy:
    - docker login -u anita15docker -p Jesusdocker

deploy:
    provider: script
    script: docker push anita15docker/node
    on:
      branch: main